all: compile limk

compile:
	g++ main.cpp -I"C:\Users\RedLava\Documents\libraries\SFML-2.5.1\include" -DSFML_STATIC

link:
	g++ main.o -o main -L"C:\Users\RedLava\Documents\libraries\SFML-2.5.1\lib" -lsfml-graphics-s -lsfml-window-s -lsfml-system-s -lopengl32 -lfreetype -lwinmm -lgdi32 -mwindows -lsfml-main

clean:
	rm -f main *.0

/*
g++ -c main.cpp -I"C:\Users\RedLava\Documents\libraries\SFML-2.5.1\include" -DSFML_STATIC
g++ main.o -o main -L"C:\Users\RedLava\Documents\libraries\SFML-2.5.1\lib" -lsfml-graphics-s -lsfml-window-s -lsfml-system-s -lopengl32 -lfreetype -lwinmm -lgdi32 -mwindows -lsfml-main